// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-pathways.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseAnon() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
}
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data) }],
    structuredContent: { data }
  };
}
function err(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-pathways.ts
var list_pathways_default = defineTool({
  name: "list_pathways",
  title: "List pathways",
  description: "List the CBC senior-school pathways (STEM, Arts & Sports, Social Sciences) with descriptions, careers, and progression.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await supabaseAnon().from("pathways").select("*");
    return error ? err(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/list-subjects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_subjects_default = defineTool2({
  name: "list_subjects",
  title: "List subjects",
  description: "List all Grade 9 subjects with their descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await supabaseAnon().from("subjects").select("*");
    return error ? err(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's profile (full name, school, KCPE index) and role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profile, role] = await Promise.all([
      sb.from("profiles").select("*").eq("user_id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId).maybeSingle()
    ]);
    if (profile.error) return err(profile.error.message);
    return ok({ profile: profile.data, role: role.data?.role ?? null });
  }
});

// src/lib/mcp/tools/get-my-results.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_results_default = defineTool4({
  name: "get_my_results",
  title: "Get my results",
  description: "Get the signed-in student's academic results with subject names and scores. Only returns rows visible under row-level security.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("results").select("id, score, verified, subjects(name)").eq("student_id", ctx.getUserId());
    return error ? err(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/get-my-recommendations.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_recommendations_default = defineTool5({
  name: "get_my_recommendations",
  title: "Get my pathway recommendations",
  description: "Get the signed-in student's computed pathway recommendations with academic score, interest score, final score, confidence, and explanation.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("recommendations").select("academic_score, interest_score, final_score, confidence, explanation, pathways(name, color)").eq("student_id", ctx.getUserId()).order("final_score", { ascending: false });
    return error ? err(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/get-my-applications.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_applications_default = defineTool6({
  name: "get_my_applications",
  title: "Get my pathway applications",
  description: "Get the signed-in student's pathway applications with status, chosen pathway, and any admin notes on adjustments.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("applications").select("id, status, admin_notes, created_at, chosen_pathway:chosen_pathway_id(name), recommended_pathway:recommended_pathway_id(name)").eq("student_id", ctx.getUserId()).order("created_at", { ascending: false });
    return error ? err(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/list-my-inquiries.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_inquiries_default = defineTool7({
  name: "list_my_inquiries",
  title: "List my inquiries",
  description: "List inquiries the signed-in user is involved in (as sender or recipient), most recent first.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("inquiries").select("*").order("created_at", { ascending: false });
    return error ? err(error.message) : ok(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "ocqrnbizfacdymxdpckn";
var mcp_default = defineMcp({
  name: "cbc-pathway-mcp",
  title: "CBC Pathway Guidance",
  version: "0.1.0",
  instructions: "Tools for the CBC Pathway Guidance app. Callers act as the signed-in app user; row-level security enforces per-user access. Use list_pathways and list_subjects for reference data, and the get_my_* tools to read the caller's own results, recommendations, applications, and inquiries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_pathways_default,
    list_subjects_default,
    get_my_profile_default,
    get_my_results_default,
    get_my_recommendations_default,
    get_my_applications_default,
    list_my_inquiries_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
